In [6]:
import numpy as np
#1. Create a null vector of size 10 but the fifth value which is 1
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [7]:
#2.Create a vector with values ranging from 10 to 49
vec=np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#3.Create a 3x3 matrix with values ranging from 0 to 8
mat=np.arange(0,9).reshape(3,3)
print(mat)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [10]:
#4.Find indices of non-zero elements from [1,2,0,0,4,0]
arr=[1,2,0,0,4,0]
ind=np.nonzero(arr)
print(ind)

(array([0, 1, 4], dtype=int64),)


In [18]:
#5.Create a 10x10 array with random values and find the minimum and maximum values
arr1=np.random.random((10,10))
print('maximum value is:{}\nminimum valueis:{}'.format(arr1.max(),arr1.min()))

maximum value is:0.9975753292079779
minimum valueis:0.012277283712540554


In [23]:
#6.Create a random vector of size 30 and find the mean value.
arr2=np.random.random(30)
print('mean value is:{}'.format(arr2.mean()))

mean value is:0.388749319689113
